# Generated by Django 3.1.7 on 2021-07-04 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCatagorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_catagorie_name', models.CharField(max_length=100)),
                ('sub_catagorie_decription', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MainCatagorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagorie_name', models.CharField(max_length=100)),
                ('catagorie_decription', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('subcatagory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_catagorie', to='main.subcatagorie')),
            ],
        ),
    ]
