# Generated by Django 3.2.5 on 2021-07-04 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('decription', models.TextField(blank=True, null=True)),
                ('created_date', models.DateField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='buyer',
            options={'verbose_name': 'Buyer'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'verbose_name': 'Seller'},
        ),
        migrations.RenameField(
            model_name='subcatagorie',
            old_name='sub_catagorie_decription',
            new_name='decription',
        ),
        migrations.RenameField(
            model_name='subcatagorie',
            old_name='sub_catagorie_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='subcatagorie',
            name='main_catagorie',
        ),
        migrations.DeleteModel(
            name='MainCatagorie',
        ),
        migrations.AddField(
            model_name='subcatagorie',
            name='catagorie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='main.catagorie'),
            preserve_default=False,
        ),
    ]
