# Generated by Django 3.2.5 on 2021-07-04 08:26

from django.db import migrations
import main.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210704_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcatagorie',
            name='field',
        ),
        migrations.AddField(
            model_name='subcatagorie',
            name='fields',
            field=main.db_fields.ListField(default='', help_text='comma separated value to store list of attributes ad must contain.', token=','),
            preserve_default=False,
        ),
    ]
