# Generated by Django 3.2.5 on 2021-07-04 08:58

from django.db import migrations, models
import django.db.models.deletion
import main.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210704_0826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Adress',
        ),
        migrations.AddField(
            model_name='customuser',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subcatagorie',
            name='fields',
            field=main.db_fields.ListField(help_text='comma separated value to store list of attributes ad must contain. Ex brand, color, size', max_length=4294967296, token=','),
        ),
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media/product_images')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='media/product_files')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('data', models.JSONField()),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.seller')),
                ('sub_catagorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcatagorie')),
            ],
        ),
    ]
