# Generated by Django 3.2.5 on 2021-07-04 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210704_0858'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdAdress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='ad',
            name='location',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='add_location', to='main.adadress'),
            preserve_default=False,
        ),
    ]
