# Generated by Django 3.2.5 on 2021-07-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210704_0918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='location',
        ),
        migrations.AddField(
            model_name='ad',
            name='area',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='city',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ad',
            name='state',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='AdAdress',
        ),
    ]
